baseurl: ''
url: 'https://gurcoff.com'
repository : “Klerpson/gurcoff"
name: Heladería GurCoff San Agustín Huila
author: Julian Franco
# email: info@enpitalito.com
title: Heladería GurCoff de San Agustín Huila
yotube: https://www.youtube.com/channel/UCiXWpAvZiAxwv7uzBGBagwQ?view_as=subscriber
facebook: https://www.facebook.com/gurcoffheladeria
instagram: https://instagram.com/gurcoff
tripadvisor: https://www.tripadvisor.co/Restaurant_Review-g445060-d19216448-Reviews-Gurcoff-San_Agustin_Huila_Department.html?m=19905
whatsapp: https://wa.me/573124489392
minegocio: https://g.page/gurcoffheladeria/review?rc
tel: tel://+573115245225
maps: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3987.6584587940297!2d-76.27689088546066!3d1.8853570986254224!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e257ba38eb5671d%3A0xabb8c090758c852!2sGurCoff%20San%20Agust%C3%ADn%20Huila!5e0!3m2!1ses-419!2sco!4v1629294844594!5m2!1ses-419!2sco

permalink: :slug

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []