baseurl: ''
url: 'https://gurcoff.com'
name: Heladería GurCoff San Agustín Huila
author: Julian Franco
# email: info@enpitalito.com
title: Heladería GurCoff de San Agustín Huila
yotube: https://www.youtube.com/channel/UCiXWpAvZiAxwv7uzBGBagwQ?view_as=subscriber
facebook: https://facebook.com/gurcoff
instagram: https://instagram.com/gurcoff
tripadvisor: https://www.tripadvisor.co/Restaurant_Review-g445060-d19216448-Reviews-Gurcoff-San_Agustin_Huila_Department.html?m=19905
whatsapp: https://wa.me/573115245225
minegocio: https://g.page/gurcoffheladeria/review?rc
# tel: tel://+573115245225
maps: https://g.page/gurcoffheladeria?share

permalink: :slug

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []