baseurl: ''
url: 'https://gurcoff.com'
repository : “Klerpson/gurcoff"
name: Heladería GurCoff
author: Julian Franco
# email: info@enpitalito.com
title: Heladería GurCoff
facebook: https://www.facebook.com/gurcoff
instagram: https://instagram.com/gurcoff
whatsapp: https://wa.me/573026370737
minegocio: https://g.page/gurcoffheladeria/review?rc
tel: tel://+573026370737
sanagustin: https://goo.gl/maps/KbHfVC77cpEXGDSo6
pitalito: https://goo.gl/maps/RQ6tyv3DTMHLY6P69
permalink: /:slug

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "articulo"
      excerpt_separator: <!-- excerpt -->
