baseurl: ''
url: 'https://gurcoff.com'
name: 'gurcoff.com'
author: Juli - GurCoff
instagram: https://www.instagram.com/gurcoff
facebook: https://www.facebook.com/gurcoff

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []
